# Generated by Django 2.2.5 on 2022-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20220119_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='company',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
